# Student Dataset Cleaning using Pandas
This notebook identifies missing values, removes duplicates, replaces missing Attendance with mean, and replaces missing Marks with median.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Creating Student DataFrame
data = {
    'Student_ID': [81, 90, 121, 124, 125, 153],
    'Name': ['Harshita', 'Jahnavee', 'Pankhuri', 'Pragati', 'Pragya', 'Sakshi'],
    'Marks': [85, None, 78, 90, None, None],
    'Attendance': [92, 88, None, 95, 85, 85]
}

df = pd.DataFrame(data)
df

   Student_ID      Name  Marks  Attendance
0          81  Harshita   85.0        92.0
1          90  Jahnavee    NaN        88.0
2         121  Pankhuri   78.0         NaN
3         124   Pragati   90.0        95.0
4         125    Pragya    NaN        85.0
5         153    Sakshi    NaN        85.0

In [ ]:
# Identify missing values
df.isnull().sum()

Student_ID    0
Name          0
Marks         3
Attendance    1
dtype: int64

In [ ]:
# Remove duplicate rows
df = df.drop_duplicates()
df

   Student_ID      Name  Marks  Attendance
0          81  Harshita   85.0        92.0
1          90  Jahnavee    NaN        88.0
2         121  Pankhuri   78.0         NaN
3         124   Pragati   90.0        95.0
4         125    Pragya    NaN        85.0
5         153    Sakshi    NaN        85.0

In [ ]:
# Replace missing Attendance with mean
df['Attendance'].fillna(df['Attendance'].mean(), inplace=True)
df

/tmp/ipython-input-4243850884.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Attendance'].fillna(df['Attendance'].mean(), inplace=True)

   Student_ID      Name  Marks  Attendance
0          81  Harshita   85.0        92.0
1          90  Jahnavee    NaN        88.0
2         121  Pankhuri   78.0        89.0
3         124   Pragati   90.0        95.0
4         125    Pragya    NaN        85.0
5         153    Sakshi    NaN        85.0

In [ ]:
# Replace missing Marks with median
df['Marks'].fillna(df['Marks'].median(), inplace=True)
df

/tmp/ipython-input-1870702586.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Marks'].fillna(df['Marks'].median(), inplace=True)

   Student_ID      Name  Marks  Attendance
0          81  Harshita   85.0        92.0
1          90  Jahnavee   85.0        88.0
2         121  Pankhuri   78.0        89.0
3         124   Pragati   90.0        95.0
4         125    Pragya   85.0        85.0
5         153    Sakshi   85.0        85.0

In [ ]:
# Final Cleaned Dataset
df

   Student_ID      Name  Marks  Attendance
0          81  Harshita   85.0        92.0
1          90  Jahnavee   85.0        88.0
2         121  Pankhuri   78.0        89.0
3         124   Pragati   90.0        95.0
4         125    Pragya   85.0        85.0
5         153    Sakshi   85.0        85.0